server:
  port: 9090

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: cryptocurrency
          uri: lb://cryptocurrency
          predicates:
            - Path=/main/**



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: true
    register-with-eureka: true

