server:
  port: 8082

spring:
  application:
    name: CryptoCurrencyApp

eureka:
  instante:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    fetch-registry: true
    register-with-eureka: true
